10000			Number of timesteps
86400.0			Timestep length [s]
20			Substep intervals
50			Timestep output intervals
7			Index of time-stepping method
0.01			Temperature change tolerance
True			Doubled radiation grid
4			HRT calc type index [two-column day-night]
4			No. SZAs [solar zenith angles] used in avg
True			Include radiative hrt
True			Include convective hrt
False			Include conductive heating rates
7.811595571071125e+24			Mass of planet [kg]
209260.80000000002			Length of day [s]
1.0			Length of year [days]
0			Orbital calc type [fixed orbital distance]
0.0158			Distance from Star [AU]
10.65			Surface gravity [m/s^2]
6990.000000000001			Planet radius [km]
31.63843524999342			atm mean mol wgt [g/mol]
1			No. major atm gases
4			***GAS ABSORBER INDEX*** [o2]
1.0			Mixing ratio
0			Pressure jacobians? [0 = None; 1 = Radiance; 2 = Flux]
2			Temperature jacobians? [0 = None; 1 = Radiance; 2 = Flux]
0.1			Fractional dtemp
1.0			Solar tolerance [0-1]
0.03			Thermal tolerance [0-1]
3			List directed input
/gscratch/vsm/gialluca/VPLModelingTools_Dev/AtmProfiles/PT_profile_dayside_Test2colmode.pt
1			Lines to skip
1,2			columns of P,T
100000.			Scale to Pa
362.14			Surface temperature [K]
31.63843524999342			atm mean mol wgt [g/mol]
1			No. major atm gases
4			***GAS ABSORBER INDEX*** [o2]
1.0			Mixing ratio
0			Pressure jacobians? [0 = None; 1 = Radiance; 2 = Flux]
2			Temperature jacobians? [0 = None; 1 = Radiance; 2 = Flux]
0.1			Fractional dtemp
1.0			Solar tolerance [0-1]
0.03			Thermal tolerance [0-1]
3			List directed input
/gscratch/vsm/gialluca/VPLModelingTools_Dev/AtmProfiles/PT_profile_dayside_Test2colmode.pt
1			Lines to skip
1,2			columns of P,T
100000.			Scale to Pa
362.14			Surface temperature [K]
0.0			Internal surface flux [W/m2]
2			Convective type [1 = adjustment; 2 = Mixing length scheme; 3 = turbulent; 4 = moist mixing]
3			Mixing length type [1 = fixed; 2 = prop to scale height; 3 = Blackadar aymptotic ML]
0.01			Mixing length proportionality
0.5			Minimum eddy diffusivity [m2/s]
10.0			Surface Wind Speed [m/s]
0.0002			Surface roughness height [m]
0			No. condensibles
5			Advection type [1 = const diffusion]
1.0			Advection constant / diffusion parameter
1			Generate fluxes using SMART
3			******NO. ABSORBING GASES******
7			************HITRAN GAS CODE [O2]*************
0			Mixing ratio jacobians [0 = None; 1 = Radiance; 2 = Flux]
3			No. of abs coeff types
1			HITRAN Line Absorbers
2			Dont compute absorption coefficients
/gscratch/vsm/gialluca/VPLModelingTools_Dev/LinebyLine_absFiles/Test2colmode/O2_Test2colmode.abs
2			Collisionally-induced absorption [CIA] files
/gscratch/vsm/gialluca/VPLModelingTools_Dev/xsec/o2-o2_abs.cia
3			UV-VIS absorption cross sections
/gscratch/vsm/gialluca/VPLModelingTools_Dev/xsec/o2xsec.dat
3			List directed input
/gscratch/vsm/gialluca/VPLModelingTools_Dev/AtmProfiles/MixingRs_Test2colmode.dat
1 			Lines to skip
1			Use pressure coordinate
1,2			columns of P,rmix
1			Mixing type [1 = volume; 2 = mass]
100000.,1.0			scale P and rmix
1			************HITRAN GAS CODE [H2O]*************
0			Mixing ratio jacobians [0 = None; 1 = Radiance; 2 = Flux]
2			No. of abs coeff types
1			HITRAN Line Absorbers
2			Dont compute absorption coefficients
/gscratch/vsm/gialluca/VPLModelingTools_Dev/LinebyLine_absFiles/Test2colmode/H2O_Test2colmode.abs
3			UV-VIS absorption cross sections
/gscratch/vsm/gialluca/VPLModelingTools_Dev/xsec/h2oxsec.dat
3			List directed input
/gscratch/vsm/gialluca/VPLModelingTools_Dev/AtmProfiles/MixingRs_Test2colmode.dat
1 			Lines to skip
1			Use pressure coordinate
1,3			columns of P,rmix
1			Mixing type [1 = volume; 2 = mass]
100000.,1.0			scale P and rmix
3			************HITRAN GAS CODE [O3]*************
0			Mixing ratio jacobians [0 = None; 1 = Radiance; 2 = Flux]
2			No. of abs coeff types
1			HITRAN Line Absorbers
2			Dont compute absorption coefficients
/gscratch/vsm/gialluca/VPLModelingTools_Dev/LinebyLine_absFiles/Test2colmode/O3_Test2colmode.abs
3			UV-VIS absorption cross sections
/gscratch/vsm/gialluca/VPLModelingTools_Dev/xsec/o3xsec.dat
3			List directed input
/gscratch/vsm/gialluca/VPLModelingTools_Dev/AtmProfiles/MixingRs_Test2colmode.dat
1 			Lines to skip
1			Use pressure coordinate
1,4			columns of P,rmix
1			Mixing type [1 = volume; 2 = mass]
100000.,1.0			scale P and rmix
0			******NO. AEROSOLS******
0			Lambertian surface
0			No albedo jacobians
3			List directed input
/gscratch/vsm/gialluca/VPLModelingTools_Dev/albedo/basalt_fresh.alb
16			Lines to skip
1,2			columns of wl, albedo
1			Wavelength
1.0			Convert to microns
1.0			Scale albedo
3			******NO. ABSORBING GASES******
7			************HITRAN GAS CODE [O2]*************
0			Mixing ratio jacobians [0 = None; 1 = Radiance; 2 = Flux]
3			No. of abs coeff types
1			HITRAN Line Absorbers
2			Dont compute absorption coefficients
/gscratch/vsm/gialluca/VPLModelingTools_Dev/LinebyLine_absFiles/Test2colmode/O2_Test2colmode.abs
2			Collisionally-induced absorption [CIA] files
/gscratch/vsm/gialluca/VPLModelingTools_Dev/xsec/o2-o2_abs.cia
3			UV-VIS absorption cross sections
/gscratch/vsm/gialluca/VPLModelingTools_Dev/xsec/o2xsec.dat
3			List directed input
/gscratch/vsm/gialluca/VPLModelingTools_Dev/AtmProfiles/MixingRs_Test2colmode.dat
1 			Lines to skip
1			Use pressure coordinate
1,2			columns of P,rmix
1			Mixing type [1 = volume; 2 = mass]
100000.,1.0			scale P and rmix
1			************HITRAN GAS CODE [H2O]*************
0			Mixing ratio jacobians [0 = None; 1 = Radiance; 2 = Flux]
2			No. of abs coeff types
1			HITRAN Line Absorbers
2			Dont compute absorption coefficients
/gscratch/vsm/gialluca/VPLModelingTools_Dev/LinebyLine_absFiles/Test2colmode/H2O_Test2colmode.abs
3			UV-VIS absorption cross sections
/gscratch/vsm/gialluca/VPLModelingTools_Dev/xsec/h2oxsec.dat
3			List directed input
/gscratch/vsm/gialluca/VPLModelingTools_Dev/AtmProfiles/MixingRs_Test2colmode.dat
1 			Lines to skip
1			Use pressure coordinate
1,3			columns of P,rmix
1			Mixing type [1 = volume; 2 = mass]
100000.,1.0			scale P and rmix
3			************HITRAN GAS CODE [O3]*************
0			Mixing ratio jacobians [0 = None; 1 = Radiance; 2 = Flux]
2			No. of abs coeff types
1			HITRAN Line Absorbers
2			Dont compute absorption coefficients
/gscratch/vsm/gialluca/VPLModelingTools_Dev/LinebyLine_absFiles/Test2colmode/O3_Test2colmode.abs
3			UV-VIS absorption cross sections
/gscratch/vsm/gialluca/VPLModelingTools_Dev/xsec/o3xsec.dat
3			List directed input
/gscratch/vsm/gialluca/VPLModelingTools_Dev/AtmProfiles/MixingRs_Test2colmode.dat
1 			Lines to skip
1			Use pressure coordinate
1,4			columns of P,rmix
1			Mixing type [1 = volume; 2 = mass]
100000.,1.0			scale P and rmix
0			******NO. AEROSOLS******
0			Lambertian surface
0			No albedo jacobians
3			List directed input
/gscratch/vsm/gialluca/VPLModelingTools_Dev/albedo/basalt_fresh.alb
16			Lines to skip
1,2			columns of wl, albedo
1			Wavelength
1.0			Convert to microns
1.0			Scale albedo
4			No. of Streams
3			Sources: 1) Solar, 2) thermal, 3) both
3			List directed input
/gscratch/vsm/gialluca/StellarSpectra/TRAPPIST-1_2020.dat
10			Lines to skip
2			Solar flux units
1			Solar spectral units
1.0			Conversion factor to microns
1,2			Cols of wn and flux
1			Outputs [fluxes]
1			No. of output azimuth angles
0.0			Azimuth
1			Outputs [TOA]
2			Output units [radiance]
40.0,5000.0			Thermal min, max wn [cm^-1]
300.0, 50000.0			Solar min, max wn [cm^-1]
2			Triangular slit function
10.0			Solar HWHM
10.0			Solar resolution
1.0			Thermal HWHM
1.0			Thermal resolution
0.5			Tau error
0.35			Single scattering error
0.35			Asymmetry parameter error
0.25			Albedo error
3			1)ASCII 3) binary no header output
/gscratch/vsm/gialluca/VPLModelingTools_Dev/ModelRunOutputs/Test2colmode/vpl_2column_climate_Test2colmode
2			Overwrite existing files
